seed: 42
epochs: 800
batch_size: 128
num_workers: 4
device: "cuda"
learning_rates:
  - 0.001
  - 0.005
  - 0.01
  - 0.1
weight_decay: 0.0
log_interval: 50
val_interval: 1
checkpoint_interval: 1
max_checkpoints: 5
data_root: "./data"
output_dir: "./output"
model: "ResNet18"
loss_functions:
  - "cross_entropy"
  - "mse"
optimizers:
  - "adam"
  - "sgd"
